#Spectate Addon for MBedwars by dejwideek

#Hex color: <SOLID:(hex without #)>
#Example: "<SOLID:fdfdfd>hex color"

#Hex gradient color:
#- start variable: <GRADIENT:(hex without #)>
#- end variable: </GRADIENT:(hex without #)>
#Example: "<GRADIENT:000000>gradient</GRADIENT:ffffff>"

#Hex rainbow color:
#- start variable: <RAINBOW(saturation value)>
#- end variable: </RAINBOW>
#Smaller value: darker
#Higher value: brighter
#Example: "<RAINBOW1>rainbow</RAINBOW>"

#This features works only on 1.16+ version

#Don't change this!
config-version: 1

#Permissions
Permissions:
  Spectate: "bw.spectate"
  Reload: "bw.spectaddon.reload"

#Messages
Messages:
  Usage: "&cUsage: /watch <player>"
  Yourself: "&cYou cannot spectate yourself!"
  Not-Found: "&cThis player isn't online!"
  No-Inside-Arena: "&cThis player isn't playing!"
  Already-Ending: "&cThis player's game is over!"

  #Available placeholder: %permission%
  No-Permission: "&cYou must have permission &4%permission% &cto do this!"

  #Available placeholders: %player%, %arena%
  Teleported: "&eTeleported to &6%player% &7(&c%arena%&7)"

  Reloaded: "&eSuccessfully reloaded configuration file!"
