name: MBedwarsSpectateAddon
version: 2.0.0
authors: [dejwideek]
depend: [MBedwars]
main: pl.dejwideek.mbwspectateaddon.SpectateAddon
commands:
  watch:
    aliases:
      - spectate
      - spec
      - spect
    description: Watch player
  spectaddonreload:
    aliases:
      - spectateaddonreload
      - sareload
    description: Reload config file