name: MBedwarsSpectateAddon
version: 1.2.0
authors: [dejwideek]
depend: [MBedwars]
main: pl.dejwideek.mbwspectateaddon.SpectateAddon
commands:
  watch:
    aliases:
      - spectate
      - spec
      - spect
    description: Watch player